spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/contask
    username: postgres
    password: 0rr3qu14
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false 
server:
  port: 8081